### ISSUE TITLE
Suggest to rename this repo

### ISSUE THREAD

**Issue by Goooler** [longphanmn/b450m#2]
I suggest you rename this repo like [Hackintosh-Ryzen-MSI-B450I](https://github.com/portrayer/Hackintosh-Ryzen-MSI-B450I) and add topics for more people to find this.

![image](https://user-images.githubusercontent.com/10363352/136883872-6dea35f0-e3f1-4572-a1dd-a23ade5ceb21.png)

**Comment by longphanmn** [comment]
Done
